name: Changelog

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  build:
    name: Check changelog entry

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check CHANGES.md changed
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-needed') }}
        run: |
          ! git fetch --prune --depth=1 origin ${{ github.base_ref }}
          ! git diff --exit-code origin/${{ github.base_ref }} -- CHANGES.md
